package com.example.pillawebappbooks.controllers;

import com.example.pillawebappbooks.dao.UserDao;
import com.example.pillawebappbooks.models.User;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.*;

import javax.servlet.http.HttpSession;
import javax.validation.Valid;

@Controller
@RequestMapping("/user")
public class UserController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserDao userRepository;

    @RequestMapping("/signin")
    public String showLoginPage(HttpSession session) {
        if(session.getAttribute("loggedUser") != null){
            return "redirect:/books/";
        }
        return "login";
    }

    @ModelAttribute
    public void checkSessionUser(HttpSession session, Model model) {
        User loggedUser = (User) session.getAttribute("loggedUser");

        if (loggedUser == null) {
            model.addAttribute("error", "You are not logged in.");
        } else {
            model.addAttribute("loggedUser", loggedUser);
            model.addAttribute("username", loggedUser.getUsername());
        }
    }


    @RequestMapping(value = "/signin",method = RequestMethod.POST)
    public String login(@RequestParam("username") String username, @RequestParam("password") String password, HttpSession session) {
        User user = userRepository.login(username, password);

        if(user == null)
            return "redirect:/login";
        else {
            session.setAttribute("loggedUser", user);

            return "redirect:/books/";
        }
    }

    @RequestMapping(value = "/signup")
    public String signupPage(User user) {
        return "signup";
    }

    @PostMapping("/signup")
    public String postSignup(@Valid User user, BindingResult bindingResult, Model model, HttpSession session){

        if(bindingResult.hasErrors()){
            return "signup";
        }

        userRepository.save(user);
        session.setAttribute("loggedUser", user);

        model.addAttribute("msg", "Informazioni salvate");
        return "redirect:/";
    }

    @RequestMapping("/logout")
    public String logout(HttpSession session) {
        session.setAttribute("loggedUser", null);
        return "redirect:/user/signin";
    }

    @RequestMapping("/allusers")
    public String getAllUsers(Model model) {
        model.addAttribute("users", userRepository.findAll());
        return "userslist";
    }

    @RequestMapping("/{id}")
    public String getUser(@PathVariable("id") Long id, Model model) {
        User user = userRepository.findById(id).get();
        model.addAttribute("user", user);
        return "user";
    }


}